import React, { Component } from "react";
import { Platform, StyleSheet, Text, View } from "react-native";
import Animation1 from "./src/Animation1";
import Animation2 from "./src/Animation2";
import Animation3 from "./src/Animation3";
import Animation4 from "./src/Animation4";
import Animation5 from "./src/Animation5";
import Animation6 from "./src/Animation6";
import Animation7 from "./src/Animation7";
import Animation8 from "./src/Animation8";
import Animation9 from "./src/Animation9";
import Animation10 from "./src/Animation10";
import Animation11 from "./src/Animation11";
import Animation12 from "./src/Animation12";
import Animation17Parallel from "./src/Animation17Parallel";
import Animation18Sequence from "./src/Animation18Sequence";
import Animation19Stagger from "./src/Animation19Stagger";
import Animation20Delay from "./src/Animation20Delay";
import Animation21 from "./src/Animation21";
import Animation22 from "./src/Animation22";
import Animation23 from "./src/Animation23";
import Animation24 from "./src/Animation24";
import Animation27Button from "./src/Animation27Button";
import Animation29D3 from "./src/Animation29D3";
import Animation30SVGD3 from "./src/Animation30SVGD3";
import Animation31ART from "./src/Animation31ART";
import Animation32Flubber from "./src/Animation32Flubber";
import AnimationProject1 from "./src/AnimationProject1";
import AnimationProject2 from "./src/AnimationProject2";
import Animation37 from "./src/Animation37";
import Animation39MessengerHead from "./src/Animation39MessengerHead";
import Animation45ProgressBtn from "./src/Animation45ProgressBtn";
import Animation63SendBtn from "./src/Animation63SendBtn";
import Animation57EvolvingButton from "./src/Animation57EvolvingButton";
import AnimationHeart from "./src/AnimationHeart";
import AnimatedSnow from "./src/SnowFallAnimation/AnimatedSnow";
import AnimationHeartTap from "./src/HeartTap/AnimationHeartTap";
import PhotoGrid from "./src/PhotoGrid";
import SnapchatUI from "./src/snapchat/SnapchatUI";
import IGDoubleTap from "./src/InstagramTap/src";
import ContactList from "./src/SearchableContactList/ContactList";
import LoginForm from "./src/LoginForm";
import FbImages from "./src/FacebookPostImageGrid";
import CallScreen from "./src/WhatsAppCallScreen";
import Chat from "./src/ChatUI";

export default class App extends Component {
  render() {
    // return <Animation1 />;
    // return <Animation2 />;
    // return <Animation3 />;
    // return <Animation4 />;
    // return <Animation5 />;
    // return <Animation6 />;
    // return <Animation7 />;
    // return <Animation8 />;
    // return <Animation9 />;
    // return <Animation10 />;
    // return <Animation11 />;
    // return <Animation12 />;
    // return <Animation17Parallel />;
    // return <Animation18Sequence />;
    // return <Animation19Stagger />;
    // return <Animation20Delay />;
    // return <Animation21 />;
    // return <Animation22 />;
    // return <Animation23 />;
    // return <Animation24 />;
    // return <Animation27Button />;
    // return <Animation29D3 />;
    // return <Animation30SVGD3 />;
    // return <Animation31ART />;
    // return <Animation32Flubber />;
    // return <AnimationProject1 />;
    // return <AnimationProject2 />;
    // return <Animation37 />;
    // return <Animation39MessengerHead />;
    // return <Animation45ProgressBtn   />;
    // return <Animation63SendBtn />;
    // return <Animation57EvolvingButton />;
    // return <AnimationHeart />;
    // return <AnimationHeartTap />;
    // return <PhotoGrid />;
    // return <AnimatedSnow />;
    // return <SnapchatUI />;
    // return <IGDoubleTap />;
    // return <ContactList />;
    // return <LoginForm />;
    // return <FbImages />;
    // return <CallScreen />;
    return <Chat />;
  }
}

const styles = StyleSheet.create({});
